# Generated by Django 5.1.5 on 2025-02-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.DecimalField(decimal_places=3, max_digits=25)),
                ('input_unit', models.CharField(choices=[('-', '-'), ('millimeter', 'Millimeter'), ('centimeter', 'Centimeter'), ('meter', 'Meter'), ('kilometer', 'Kilometer'), ('inch', 'Inch'), ('foot', 'Foot'), ('yard', 'Yard'), ('mile', 'Mile')], default='-', max_length=50)),
                ('output_unit', models.CharField(choices=[('-', '-'), ('millimeter', 'Millimeter'), ('centimeter', 'Centimeter'), ('meter', 'Meter'), ('kilometer', 'Kilometer'), ('inch', 'Inch'), ('foot', 'Foot'), ('yard', 'Yard'), ('mile', 'Mile')], default='-', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConvertMass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.DecimalField(decimal_places=3, max_digits=25)),
                ('input_unit', models.CharField(choices=[('-', '-'), ('milligram', 'Milligram'), ('gram', 'Gram'), ('kilogram', 'Kilogram'), ('ounce', 'Ounce'), ('pound', 'Pound')], default='-', max_length=50)),
                ('output_unit', models.CharField(choices=[('-', '-'), ('milligram', 'Milligram'), ('gram', 'Gram'), ('kilogram', 'Kilogram'), ('ounce', 'Ounce'), ('pound', 'Pound')], default='-', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConvertTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.DecimalField(decimal_places=3, max_digits=25)),
                ('input_unit', models.CharField(choices=[('-', '-'), ('celsius', 'Celsius'), ('fahrenheit', 'Fahrenheit'), ('kelvin', 'Kelvin')], default='-', max_length=50)),
                ('output_unit', models.CharField(choices=[('-', '-'), ('celsius', 'Celsius'), ('fahrenheit', 'Fahrenheit'), ('kelvin', 'Kelvin')], default='-', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
