# Generated by Django 5.1.5 on 2025-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unit_Converter', '0002_convertlength_created_at_convertmass_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertlength',
            name='input_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='convertmass',
            name='input_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='converttemperature',
            name='input_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
